#!/usr/bin/env node

require('@babel/register');

const schemaGenerator = require('./src/schema-generator');

schemaGenerator.dialect = 'postgres';
schemaGenerator.version = 'v2';
schemaGenerator.tableSchema = 'organization';
schemaGenerator.newOrganization = 1;

const diff = schemaGenerator.compareOrganization();

console.log(diff.join('\n\n'));
